##
## Dockerfile to generate a Docker image for nginx - to be used in a GeoDjango project##
# Start from the official Nginx image
FROM nginx
MAINTAINER Mark Foley
# Get rid of old default file and copy our config so that nginx can pick it up
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.old
COPY .cache/nginx_config.conf /etc/nginx/conf.d
COPY /static/ /usr/share/nginx/html/static